Repository ArtemKiyashko/AmSpaceTools, pull requests merged in 2018-12, with the labels that each got.

#50 handle new default password the same as old.
  AmSpaceTools/ViewModels/PeopleUploadViewModel.cs
  ExcelWorker/Models/SapPersonExcelRow.cs
Labels: bug

#54 Request wrapper unit tests #52
  AmSpaceClient/AmSpaceClient.cs
  AmSpaceClient/AmSpaceClient.csproj
  AmSpaceClient/IRequestWrapper.cs
  AmSpaceClient/RequestWrapper.cs
  AmSpaceClient/ResponseValidator.cs
  AmSpaceClient/packages.config
  AmSpaceModels/AmSpaceModels.csproj
  AmSpaceModels/packages.config
  AmSpaceTools/AmSpaceTools.csproj
  AmSpaceTools/packages.config
  AmspaceClientUnitTests/AmspaceClientUnitTests.csproj
  AmspaceClientUnitTests/CommonTests.cs
  AmspaceClientUnitTests/RequestWrapperTests.cs
  AmspaceClientUnitTests/ResponseValidatorTests.cs
  AmspaceClientUnitTests/packages.config
Labels: tests

#55 Feature job map uploading
  AmSpaceModels/AmSpaceModels.csproj
  AmSpaceModels/JobMap/TranslationsMap.cs
  AmSpaceTools/AmSpaceTools.csproj
  AmSpaceTools/MainWindow.xaml
  AmSpaceTools/Properties/Resources.Designer.cs
  AmSpaceTools/Properties/Resources.resx
  AmSpaceTools/Properties/Resources.ru.Designer.cs
  AmSpaceTools/Properties/Resources.ru.resx
  AmSpaceTools/ViewModels/BaseViewModel.cs
  AmSpaceTools/ViewModels/JobMapUploadViewModel.cs
  AmSpaceTools/ViewModels/LoginViewModel.cs
  AmSpaceTools/ViewModels/MainWindowViewModel.cs
  AmSpaceTools/ViewModels/ProfileViewModel.cs
  AmSpaceTools/Views/JobMapUpload.xaml
  AmSpaceTools/Views/JobMapUpload.xaml.cs
  AmSpaceTools/Views/Login.xaml
  AmSpaceTools/Views/Profile.xaml
  ExcelWorker/Models/JobMapExcelRow.cs
Labels: feature

#56 Jpa upload backend
  AmSpaceClient/AmSpaceClient.cs
  AmSpaceClient/AmSpaceClient.csproj
  AmSpaceClient/ApiEndpoints.cs
  AmSpaceClient/Extensions/MultipartFormExtensions.cs
  AmSpaceClient/FileToUpload.cs
  AmSpaceClient/IAmSpaceClient.cs
  AmSpaceClient/IRequestWrapper.cs
  AmSpaceClient/RequestWrapper.cs
  AmSpaceModels/AmSpaceModels.csproj
  AmSpaceModels/Enums/AppDataFolders.cs
  AmSpaceModels/Performance/JpaFile.cs
  AmSpaceTools/AmSpaceTools.csproj
  AmSpaceTools/Infrastructure/Converters/DecimalToStringPercentConverter.cs
  AmSpaceTools/Infrastructure/ProgressState.cs
  AmSpaceTools/ViewModels/PeopleUploadViewModel.cs
  AmSpaceTools/Views/ProgressIndicator.xaml
  AmspaceClientUnitTests/RequestWrapperTests.cs
  ExcelWorker/AmSpaceExcelWorker.cs
  ExcelWorker/EpplusExtensions.cs
  ExcelWorker/ExcelWorker.csproj
  ExcelWorker/Models/EpplusIgnoreAttribute.cs
  ExcelWorker/Services/IFileWrapper.cs
  ExcelWorker/Services/ISaveLocator.cs
  ExcelWorkerTests/CommonTests.cs
  ExcelWorkerTests/ExcelWorkerTests.csproj
  ExcelWorkerTests/Properties/Resources.Designer.cs
  ExcelWorkerTests/Properties/Resources.resx
  ExcelWorkerTests/Resources/ImportPeople_template.xlsx
  ExcelWorkerTests/Resources/example.xlsx
  ExcelWorkerTests/SapPeopleTests.cs
  ExcelWorkerTests/packages.config
Labels: feature
